// Generated by LiveScript 1.2.0
(function(){
  var InsertOP, DeleteOP;
  InsertOP = require('./insert');
  DeleteOP = require('./delete');
  exports.InsertOP = InsertOP;
  exports.insert = InsertOP;
  exports.DeleteOP = DeleteOP;
  exports['delete'] = DeleteOP;
}).call(this);
