// Generated by LiveScript 1.2.0
(function(){
  var Poke, TermUI, poke, ui;
  Poke = require('./index');
  TermUI = require('./termui');
  poke = new Poke();
  poke.activeBuffer.insert(0, 0, "Hello World!");
  ui = new TermUI(poke, process.stdin, process.stdout);
}).call(this);
