// Generated by LiveScript 1.2.0
(function(){
  var Cursor, exports;
  Cursor = (function(){
    Cursor.displayName = 'Cursor';
    var prototype = Cursor.prototype, constructor = Cursor;
    function Cursor(buffer, x, y){
      var this$ = this instanceof ctor$ ? this : new ctor$;
      this$.buffer = buffer;
      this$.x = x;
      this$.y = y;
      return this$;
    } function ctor$(){} ctor$.prototype = prototype;
    return Cursor;
  }());
  exports = module.exports = Cursor;
}).call(this);
