// Generated by LiveScript 1.2.0
(function(){
  var Selection, exports;
  Selection = (function(){
    Selection.displayName = 'Selection';
    var prototype = Selection.prototype, constructor = Selection;
    function Selection(buffer, x, y, length){
      var this$ = this instanceof ctor$ ? this : new ctor$;
      this$.buffer = buffer;
      this$.x = x;
      this$.y = y;
      this$.length = length != null ? length : 0;
      return this$;
    } function ctor$(){} ctor$.prototype = prototype;
    return Selection;
  }());
  exports = module.exports = Selection;
}).call(this);
