// Generated by LiveScript 1.2.0
(function(){
  var charms, TermUI, exports;
  charms = require('charm');
  TermUI = (function(){
    TermUI.displayName = 'TermUI';
    var prototype = TermUI.prototype, constructor = TermUI;
    function TermUI(poke, readable, writable){
      var this$ = this instanceof ctor$ ? this : new ctor$;
      this$.poke = poke;
      this$.readable = readable;
      this$.writable = writable;
      this$.redraw = bind$(this$, 'redraw', prototype);
      this$.charm = charms(this$.readable, this$.writable);
      this$.charm.reset();
      this$.charm.position(1, 1);
      this$.width = 100;
      this$.height = 30;
      this$.textX = 2;
      this$.textY = 2;
      this$.redraw();
      return this$;
    } function ctor$(){} ctor$.prototype = prototype;
    prototype.redraw = function(){
      var buffer, title, commandArea, i$, to$, i, results$ = [];
      this.charm.position(1, 1);
      buffer = this.poke.activeBuffer;
      title = "[=====[" + buffer.name() + "]=====]";
      this.charm.write("+" + repeatString$("-", (this.width - 2 - title.length) / 2) + title + repeatString$("-", (this.width - 2 - title.length) / 2) + "+\n");
      this.charm.write(repeatString$("|\n", this.height - 4));
      commandArea = repeatString$(" ", this.width - (6 + 5 * 2));
      this.charm.write("+" + repeatString$("-", (this.width - 2 - commandArea.length - 4) / 2) + "[[");
      this.charm.display('underscore');
      this.charm.write(commandArea);
      this.charm.display('reset');
      this.charm.write("]]" + repeatString$("-", (this.width - 2 - commandArea.length - 4) / 2) + "+\n");
      for (i$ = 2, to$ = this.height - 3; i$ <= to$; ++i$) {
        i = i$;
        this.charm.position(this.width, i);
        this.charm.write("|");
      }
      for (i$ = 0, to$ = this.height - this.textY - 1; i$ <= to$; ++i$) {
        i = i$;
        this.charm.position(2, i + this.textY);
        results$.push(this.charm.write(buffer.line(i)));
      }
      return results$;
    };
    return TermUI;
  }());
  exports = module.exports = TermUI;
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
  function repeatString$(str, n){
    for (var r = ''; n > 0; (n >>= 1) && (str += str)) if (n & 1) r += str;
    return r;
  }
}).call(this);
