// Generated by LiveScript 1.2.0
(function(){
  var charms, keypress, ansirecover, tuil, TUIL, TermUI, exports, toString$ = {}.toString;
  charms = require('charm');
  keypress = require('keypress');
  ansirecover = require('ansi-recover');
  tuil = TUIL = (function(){
    TUIL.displayName = 'TUIL';
    var Obj, prototype = TUIL.prototype, constructor = TUIL;
    function TUIL(def){
      var this$ = this instanceof ctor$ ? this : new ctor$;
      this$.def = def;
      this$.update = bind$(this$, 'update', prototype);
      this$.redraw = bind$(this$, 'redraw', prototype);
      this$.cursor = bind$(this$, 'cursor', prototype);
      ansirecover({
        cursor: false,
        mouse: true
      });
      this$.charm = charms(process.stdin, process.stdout);
      this$.charm.reset();
      this$.width = process.stdout.columns;
      this$.height = process.stdout.rows;
      this$.update(true);
      this$.redraw();
      process.stdout.on('resize', function(){
        this$.width = process.stdout.columns;
        this$.height = process.stdout.rows;
        this$.update(true);
        return this$.redraw();
      });
      return this$;
    } function ctor$(){} ctor$.prototype = prototype;
    prototype.cursor = function(cb){
      return this.charm.position(cb);
    };
    prototype.redraw = function(x, y){
      var i$, ref$, len$, obj, clear;
      x == null && (x = true);
      if (typeof x === 'number' && typeof y === 'number') {
        this.charm.position(x, y);
        this.charm.write(' ');
        for (i$ = 0, len$ = (ref$ = this.objs).length; i$ < len$; ++i$) {
          obj = ref$[i$];
          if (x >= obj._x && y >= obj._y && x <= obj._x + obj.width && y <= obj._y + obj.height) {
            obj.redraw();
          }
        }
      } else {
        clear = x;
        if (clear) {
          this.charm.erase('screen');
        }
        for (i$ = 0, len$ = (ref$ = this.objs).length; i$ < len$; ++i$) {
          obj = ref$[i$];
          obj.redraw(clear, !clear);
        }
      }
      return this;
    };
    prototype.update = function(redef){
      var i$, ref$, len$, obj, this$ = this;
      redef == null && (redef = false);
      if (redef) {
        this.objs = [];
        this.def.call(null, function(x, y, text){
          var obj;
          obj = new TUIL.Obj(this$, x, y, text);
          this$.objs.push(obj);
          return obj;
        });
      } else {
        for (i$ = 0, len$ = (ref$ = this.objs).length; i$ < len$; ++i$) {
          obj = ref$[i$];
          obj.update();
        }
      }
      return this;
    };
    TUIL.Obj = Obj = (function(){
      Obj.displayName = 'Obj';
      var prototype = Obj.prototype, constructor = Obj;
      function Obj(ui, x, y, text){
        var this$ = this instanceof ctor$ ? this : new ctor$;
        this$.ui = ui;
        this$.x = x;
        this$.y = y;
        this$.text = text;
        this$.update = bind$(this$, 'update', prototype);
        this$.redraw = bind$(this$, 'redraw', prototype);
        this$._oldLines = [];
        this$.update();
        return this$;
      } function ctor$(){} ctor$.prototype = prototype;
      prototype.redraw = function(force, clear){
        var i$, ref$, len$, i, line;
        force == null && (force = false);
        clear == null && (clear = true);
        if (force || (this._oldX !== this._x || this._oldY !== this._y || this._oldWidth !== this.width || this._oldHeight !== this.height || this._oldText !== this._text)) {
          if (clear && (this._oldX != null && this._oldY != null)) {
            for (i$ = 0, len$ = (ref$ = this._oldLines).length; i$ < len$; ++i$) {
              i = i$;
              line = ref$[i$];
              if (line !== this._lines[i] || this._oldX !== this._x || this._oldY !== this._y) {
                this.ui.charm.position(this._oldX, this._oldY + i);
                this.ui.charm.write(repeatString$(" ", Math.min(line.length, this.ui.width - this._x)));
              }
            }
          }
          for (i$ = 0, len$ = (ref$ = this._lines).length; i$ < len$; ++i$) {
            i = i$;
            line = ref$[i$];
            if (line !== this._oldLines[i] || force || this._oldX !== this._x || this._oldY !== this._y) {
              this.ui.charm.position(this._x, this._y + i);
              this.ui.charm.write(line.substr(0, this.ui.width - this._x));
            }
          }
          this._oldX = this._x;
          this._oldY = this._y;
          this._oldWidth = this.width;
          this._oldHeight = this.height;
          this._oldLines = this._lines.slice(0);
          this._oldText = this._text;
        }
        return this;
      };
      prototype.update = function(){
        if (typeof this.x === 'function') {
          this._x = this.x();
        } else {
          this._x = this.x;
        }
        if (typeof this.y === 'function') {
          this._y = this.y();
        } else {
          this._y = this.y;
        }
        if (typeof this.text === 'function') {
          this._text = this.text();
        } else {
          this._text = this.text.toString();
        }
        if (toString$.call(this._text).slice(8, -1) === 'Array') {
          this._lines = this._text;
          this._text = this._lines.join('\n');
        } else {
          this._lines = this._text.split(/[\n\r]/g);
        }
        this.width = Math.max.apply(Math, this._lines.map(function(it){
          return it.length;
        }));
        this.height = this._lines.length;
        return this;
      };
      return Obj;
    }());
    return TUIL;
  }());
  TermUI = (function(){
    TermUI.displayName = 'TermUI';
    var prototype = TermUI.prototype, constructor = TermUI;
    function TermUI(poke, styles){
      var rs, ws, bufferApplyHandler, this$ = this instanceof ctor$ ? this : new ctor$;
      this$.poke = poke;
      this$.styles = styles;
      this$.redraw = bind$(this$, 'redraw', prototype);
      this$._setStyle = bind$(this$, '_setStyle', prototype);
      rs = process.stdin;
      ws = process.stdout;
      this$.ui = tuil(function(def){
        this$.titleUi = def(1, 1, function(){
          return " -- " + this$.poke.activeBuffer.name();
        });
        return this$.textUi = def(1, 2, function(){
          return this$.poke.activeBuffer.lines().map(function(line, i){
            return "  " + i + " " + line;
          });
        });
      });
      bufferApplyHandler = function(){
        this$.ui.update();
        return this$.ui.redraw(false);
      };
      this$.poke.on('switch-buffer', function(newBuffer, oldBuffer){
        oldBuffer.off('apply', bufferApplyHandler);
        return newBuffer.on('apply', bufferApplyHandler);
      });
      this$.poke.activeBuffer.on('apply', bufferApplyHandler);
      this$.width = ws.columns;
      this$.height = ws.rows;
      this$.textX = 1;
      this$.textY = 1;
      this$.scrollV = 0;
      this$.scrollH = 0;
      keypress(rs);
      keypress.enableMouse(ws);
      rs.setRawMode(true);
      rs.resume();
      rs.on('keypress', function(ch, key){
        var e;
        if (key != null) {
          switch (false) {
          case !(key.ctrl && key.name === 'c'):
            rs.pause();
            process.exit();
            break;
          case ch == null:
            try {
              this$.poke.activeBuffer.insert(ch);
            } catch (e$) {
              e = e$;
              throw e;
            }
          }
        }
        return this$.ui.cursor(function(cx, cy){
          return this$.ui.redraw(cx - 1, cy);
        });
      });
      rs.on('mousepress', function(mouse){
        return this$.ui.redraw();
      });
      rs.on('end', function(){
        return keypress.disableMouse(ws);
      });
      this$.ui.redraw();
      return this$;
    } function ctor$(){} ctor$.prototype = prototype;
    prototype._setStyle = function(style){
      var i$, ref$, len$, disp, results$ = [];
      this.charm.display('reset');
      if (style.foreground != null) {
        this.charm.foreground(style.foreground);
      }
      if (style.background != null) {
        this.charm.background(style.background);
      }
      for (i$ = 0, len$ = (ref$ = style.display).length; i$ < len$; ++i$) {
        disp = ref$[i$];
        results$.push(this.charm.display(disp));
      }
      return results$;
    };
    prototype.redraw = function(){
      var buffer, gutter, res$, i$, to$, line, gutterWidth, i, results$ = [];
      this.charm.reset();
      buffer = this.poke.activeBuffer;
      res$ = [];
      for (i$ = this.scrollV, to$ = this.height - this.textY - 1 + this.scrollV; i$ <= to$; ++i$) {
        line = i$;
        res$.push((line + 1).toString());
      }
      gutter = res$;
      gutterWidth = Math.max.apply(Math, gutter.map(function(it){
        return it.length;
      })) + 2;
      for (i$ = this.scrollV, to$ = this.height - this.textY - 1 + this.scrollV; i$ <= to$; ++i$) {
        i = i$;
        this.charm.position(this.textX, i + this.textY);
        if (buffer.lines[i] != null) {
          this._setStyle(this.styles.gutterLinenum);
          this.charm.write(repeatString$(" ", gutterWidth - gutter[i].length - 1));
          this.charm.write(gutter[i] + " ");
        } else {
          this._setStyle(this.styles.gutterNoline);
          this.charm.write("~");
          this.charm.write(repeatString$(" ", gutterWidth - 1));
        }
        this._setStyle(this.styles.text);
        results$.push(this.charm.write(buffer.line(i).substr(this.scrollH)));
      }
      return results$;
    };
    return TermUI;
  }());
  exports = module.exports = TermUI;
  function bind$(obj, key, target){
    return function(){ return (target || obj)[key].apply(obj, arguments) };
  }
  function repeatString$(str, n){
    for (var r = ''; n > 0; (n >>= 1) && (str += str)) if (n & 1) r += str;
    return r;
  }
}).call(this);
