// Generated by LiveScript 1.2.0
(function(){
  var Poke, TermUI, util, poke, buffer, ui;
  Poke = require('./index');
  TermUI = require('./termui');
  util = require('util');
  function i(o){
    return console.log(util.inspect(o, {
      colors: true,
      depth: null
    }));
  }
  poke = new Poke();
  buffer = poke.activeBuffer;
  buffer.insert(0, 0, "Hello World!\nfoo\nbar\nbaz");
  buffer.commit();
  ui = new TermUI(poke, {
    title: {
      foreground: 0,
      background: 15,
      display: []
    },
    gutterLinenum: {
      foreground: 3,
      background: 0,
      display: []
    },
    gutterNoline: {
      foreground: 4,
      background: 0,
      display: []
    },
    text: {
      foreground: 15,
      background: 0,
      display: []
    }
  });
}).call(this);
