// Generated by LiveScript 1.2.0
(function(){
  var Poke, util, poke, buffer;
  Poke = require('./index');
  util = require('util');
  function i(o){
    return console.log(util.inspect(o, {
      colors: true,
      depth: null
    }));
  }
  poke = new Poke;
  buffer = poke.activeBuffer;
  buffer.insert(0, 0, "Hello World!\nfoo\nbar\nbaz");
  buffer.commit();
  buffer['delete']('end', 0, 'all');
  buffer.commit();
  i(buffer.lines);
  buffer.undo();
  i(buffer.lines);
  buffer.redo();
  i(buffer.lines);
}).call(this);
